version: '2'
services:

  db:
    image: postgres

  app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0 --pid /app/tmp/pids/server_app.pid
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  app2:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0 --pid /app/tmp/pids/server_app2.pid
    ports:
      - "3000"
    volumes:
      - .:/app
    depends_on:
      - db

  haproxy:
    build:
      context: ./haproxy
    depends_on:
     - app
    ports:
     - "80:80"
     - "70:70"
    expose:
     - "80"
     - "70"
