version: '2'
services:
  db:
    image: postgres
  haproxy:
    build: ./haproxy
    depends_on:
     - app
    ports:
     - "80:80"
     - "70:70"
    expose:
     - "80"
     - "70"
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
